# Build stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
<% if (orm === 'Prisma') { %>
COPY prisma ./prisma/
<% } %>

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:20-alpine

WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/dist ./dist
<% if (orm === 'Prisma') { %>
COPY --from=build /app/prisma ./prisma
<% } %>

RUN npm install --omit=dev

EXPOSE 3000

CMD ["npm", "start"]
